CREATE TABLE IF NOT EXISTS tracks (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    track_name_norm TEXT NOT NULL,
    mbid TEXT,
    url TEXT,
    duration INTEGER,
    streamable TEXT,
    streamable_fulltrack TEXT,
    artist_id INTEGER REFERENCES artists(id),
    artist_name TEXT NOT NULL,
    artist_name_norm TEXT NOT NULL,
    artist_mbid TEXT,
    artist_url TEXT,
    album_id INTEGER REFERENCES albums(id),
    album_title TEXT,
    album_artist TEXT,
    album_mbid TEXT,
    album_url TEXT,
    album_position TEXT,
    album_image_small TEXT,
    album_image_medium TEXT,
    album_image_large TEXT,
    album_image_extralarge TEXT,
    toptags JSONB,
    wiki_published TEXT,
    wiki_summary TEXT,
    wiki_content TEXT,
    user_loved BOOLEAN,
    user_playcount INTEGER,
    embedding VECTOR(384)
);