CREATE TABLE IF NOT EXISTS albums (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    album_name_norm TEXT NOT NULL,
    mbid TEXT,
    url TEXT,
    release_date TEXT,
    artist_id INTEGER REFERENCES artists(id),
    artist_name TEXT NOT NULL,
    artist_name_norm TEXT NOT NULL,
    image_small TEXT,
    image_medium TEXT,
    image_large TEXT,
    image_extralarge TEXT,
    listeners INTEGER,
    playcount INTEGER,
    toptags JSONB,
    tracks JSONB,
    wiki_published TEXT,
    wiki_summary TEXT,
    wiki_content TEXT,
    user_playcount INTEGER,
    embedding VECTOR(384)
);